In [ ]:
import numpy as np

#Exercise 1

In [ ]:
#ham kiem tra co la to hop tuyen tinh hay khong
def isCombination(vector, w):
  rank = np.linalg.matrix_rank(vector)
  rankw = np.linalg.matrix_rank(np.column_stack((vector, w)))
  if rank == rankw:
    return True
  else:
    return False

#cau a
v1a = np.array([1, 2, 3, 4])
v2a = np.array([-1, 0, 1, 3])
v3a = np.array([0, 5, -6, 8])

Aa = np.array([v1a, v2a, v3a]).T

wa = np.array([3, -6, 17, 11]).T

if isCombination(Aa, wa):
  print("a. is combination")
else:
  print("a. is not combination")

#cau b
v1b = np.array([1, 1, 2, 2])
v2b = np.array([2, 3, 5, 6])
v3b = np.array([2, -1, 3, 6])

Ab = np.array([v1b, v2b, v3b]).T

wb = np.array([0, 5, 3, 0])

if isCombination(Ab, wb):
  print("b. is combination")
else:
  print("b. is not combination")

#cau c
v1c = np.array([1, 1, 2, 2])
v2c = np.array([2, 3, 5, 6])
v3c = np.array([2, -1, 3, 6])

Ac = np.array([v1c, v2c, v3c]).T

wc = np.array([-1, 6, 1, -4])

if isCombination(Ac, wc):
  print("c. is combination")
else:
  print("c. is not combination")

#cau d
v1d = np.array([1, 2, 3, 4])
v2d = np.array([-1, 0, 1, 3])
v3d = np.array([0, 5, -6, 8])
v4d = np.array([1, 15, -12, 8])

Ad = np.array([v1d, v2d, v3d, v4d]).T

wd = np.array([0, -6, 17, 11])

if isCombination(Ad, wd):
  print("d. is combination")
else:
  print("d. is not combination")

a. is not combination
b. is not combination
c. is combination
d. is combination


#Exercise 2

In [ ]:
#cau a
v1a = np.array([1, -2, 0])
v2a = np.array([0, -4, 1])
v3a = np.array([1, -1, 1])

Aa = np.array([v1a, v2a, v3a]).T

rank_a = np.linalg.matrix_rank(Aa)

if rank_a == len([v1a, v2a, v3a]):
  print("a. is independent")
else:
  print("a. is dependent")

#cau b
v1b = np.array([1, 0, 2])
v2b = np.array([0, 1, 4])
v3b = np.array([2, -2, -4])

Ab = np.array([v1b, v2b, v3b]).T

rank_b = np.linalg.matrix_rank(Ab)

if rank_b == len([v1b, v2b, v3b]):
  print("b. is independent")
else:
  print("b. is dependent")

#khoi tao a, b, c
a, b, c = sp.symbols('a, b, c')

eq1 = sp.Eq(1*a + 2*c, 0)
eq2 = sp.Eq(1*b - 2*c, 0)
eq3 = sp.Eq(2*a + 4*b -4*c, 0)

sol = sp.solve((eq1, eq2, eq3), (a, b, c))
print(sol)

#cau c
v1c = np.array([1, -2, 3, 4])
v2c = np.array([2, 4, 5, 0])
v3c = np.array([-2, 0, 0, 4])
v4c = np.array([3, 2, 1, -1])

Ac = np.array([v1c, v2c, v3c, v4c])

rank_c = np.linalg.matrix_rank(Ac)

if rank_c == len([v1c, v2c, v3c, v4c]):
  print("c. is independent")
else:
  print("c. is dependent")

#cau d
v1d = np.array([0, 0, 1, 2, 3])
v2d = np.array([0, 0, 2, 3, 1])
v3d = np.array([1, 2, 3, 4, 5])
v4d = np.array([2, 1, 0, 0, 0])
v5d = np.array([-1, -3, -5, 0, 0])

Ad = np.array([v1d, v2d, v3d, v4d, v5d])

rank_d = np.linalg.matrix_rank(Ad)

if rank_d == len([v1d, v2d, v3d, v4d, v5d]):
  print("d. is independent")
else:
  print("d. is dependent")

a. is independent
b. is dependent
{a: -2*c, b: 2*c}
c. is independent
d. is independent


#Exercise 3

In [ ]:
C = np.array([
    [1, 0, 2, 3],
    [4, -1, 0, 2],
    [0, -1, -8, -10]
])

#cau a
print("----Cau a:----")
res_a = sp.Matrix(C).rref()
print("sp.Matrix(C).rref() = \n", res_a)

basisC = C[:, list(res_a[1])]
print("A basis of column space of C = \n", basisC)

#cau b
print("\n----Cau b:----")
res_b = sp.Matrix(C.T).rref()
print("sp.Matrix(C.T).rref() = \n", res_b)

basisC_T = C.T[:, list(res_b[1])]
print("A basis of row space of C = \n", basisC_T)

----Cau a:----
sp.Matrix(C).rref() = 
 (Matrix([
[1, 0, 2,  3],
[0, 1, 8, 10],
[0, 0, 0,  0]]), (0, 1))
A basis of column space of C = 
 [[ 1  0]
 [ 4 -1]
 [ 0 -1]]

----Cau b:----
sp.Matrix(C.T).rref() = 
 (Matrix([
[1, 0, -4],
[0, 1,  1],
[0, 0,  0],
[0, 0,  0]]), (0, 1))
A basis of row space of C = 
 [[ 1  4]
 [ 0 -1]
 [ 2  0]
 [ 3  2]]


#Exercise 4

In [ ]:
A = np.array([
    [1, 0, 2, 3],
    [4, -1, 0, 2],
    [0, -1, -8, -10]
])

U, s, Vt = np.linalg.svd(A)
null_space = Vt[-2:].T

v1 = null_space[:, 0]
v2 = null_space[:, 1]

print("Cau a:")
print("v1:", v1)
print("v2:", v2)

Cau a:
v1: [-0.38653914 -0.59682614 -0.51872824  0.47466521]
v2: [-0.00848703 -0.75606455  0.54583085 -0.36105823]


#Exercise 5

In [ ]:
#cau a
print("Cau a:")
w = np.array([1, 1, -1, -3]).reshape(-1, 1)
A = np.array([
    [7, 6, -4, 1],
    [-5, -1, 0, -2],
    [9, -11, 7, -3],
    [19, -9, 7, 1]
])

U, s, V = np.linalg.svd(A)
CS = U.dot(U.T.dot(w))

NS = V.T[:, s < 1e-10]

count = 0
if np.allclose(w, CS):
    print("w is in the column space of A")
    count = count + 1
else:
    print("w is not in the column space of A")

Aw = A.dot(w)
if np.allclose(Aw, np.zeros((A.shape[0], 1))):
    print("w is in the null space of A")
    count = count + 1
else:
    print("w is not in the null space of A")

if (count ==2):
    print("w is both the column space and null space of A")
else:
    print("w is not both the column space and null space of A")

#cau b
print("Cau b:")
w = np.array([1, 2, 1, 0]).reshape(-1, 1)

A = np.array([
    [-8, 5, -2, 0],
    [-5, 2, 1, -2],
    [10, -8, 6, -3],
    [3, -2, 1, 0]
])

U, s, V = np.linalg.svd(A)
CS = U.dot(U.T.dot(w))

NS = V.T[:, s < 1e-10]

count = 0
if np.allclose(w, CS):
    print("w is in the column space of A")
    count = count + 1
else:
    print("w is not in the column space of A")

Aw = A.dot(w)
if np.allclose(Aw, np.zeros((A.shape[0], 1))):
    print("w is in the null space of A")
    count = count + 1
else:
    print("w is not in the null space of A")

if (count== 2):
    print("w is both the column space and null space of A")
else:
    print("w is not both the column space and null space of A")

Cau a:
w is in the column space of A
w is not in the null space of A
w is not both the column space and null space of A
Cau b:
w is in the column space of A
w is in the null space of A
w is both the column space and null space of A


#Exercise 6

In [ ]:
A = np.array([
    [5, 1, 2, 2, 0],
    [3, 3, 2, -1, -12],
    [8, 4, 4, -5, 12],
    [2, 1, 1, 0, -2]
])

B = A[:, [0, 1, 3]]

rank_B = np.linalg.matrix_rank(B)
U, s, V = np.linalg.svd(B)
CS_B = U[:, :rank_B]

a3 = A[:, 2]
a5 = A[:, 4]

proj_a3 = CS_B.dot(np.linalg.inv(CS_B.T.dot(CS_B))).dot(CS_B.T).dot(a3)
proj_a5 = CS_B.dot(np.linalg.inv(CS_B.T.dot(CS_B))).dot(CS_B.T).dot(a5)

if np.allclose(proj_a3, a3):
    print("a3 is in the column space of B")
else:
    print("a3 is not in the column space of B")

if np.allclose(proj_a5, a5):
    print("a5 is in the column space of B")
else:
    print("a5 is not in the column space of B")

a3 is in the column space of B
a5 is in the column space of B


#Exercise 7

In [ ]:
A = np.array([
    [1, 0, 2],
    [0, 1, 4],
    [2, -2, -4]
]).T

dim_span = np.linalg.matrix_rank(A)

rref, _ = np.linalg.qr(A)
basis = rref[:, :dim_span]

print("Dimension of span =", dim_span)
print("Basis of span = \n", basis)

Dimension of span = 2
Basis of span = 
 [[-0.4472136   0.78072006]
 [-0.         -0.48795004]
 [-0.89442719 -0.39036003]]


#Exercise 8

In [ ]:
# Create the Hilbert matrix A with size 5
A = np.array([[1/(i+j-1) for j in range(1,6)] for i in range(1,6)])
print("Hilbert Matrix = \n", A)

# Create matrix B
B = np.zeros((5,5))
for i in range(5):
    for j in range(i+1):
        if j == 0 or j == i:
            B[i][j] = 1
        else:
            B[i][j] = B[i-1][j-1] + B[i-1][j]

print("\nPascal Matrix = \n", B)

# Create magic matrix C
n = 5
C = [[0 for x in range(n)] for y in range(n)]

i = n // 2
j = n - 1

num = 1
while num <= (n * n):
    if i == -1 and j == n:  
        j = n - 2
        i = 0
    else:
        if j == n:
            j = 0
        if i < 0:
            i = n - 1
    if C[i][j]:
        j -= 2
        i += 1
        continue
    else:
        C[i][j] = num
        num += 1
    j += 1
    i -= 1

arr = np.array(C).flatten()
# Reshape to square matrix
n = int(np.sqrt(len(arr)))
C_square = arr.reshape(n, n)
print("\nMagic matrix = \n", C_square)

# Find a basis for the null space of Hilbert Matrix
u, s, vh = np.linalg.svd(A)
null_space_basis_A = vh[np.sum(s > 1e-10):,:].T

# Find a basis for the null space of Pascal Matrix
u, s, vh = np.linalg.svd(B)
null_space_basis_B = vh[np.sum(s > 1e-10):,:].T

# Find a basis for the null space of Magic Matrix
u, s, vh = np.linalg.svd(C_square)
null_space_basis_C = vh[np.sum(s > 1e-10):,:].T

print("\nBasis for the null space of Hilbert Matrix:", null_space_basis_A)

print("Basis for the null space of Pascal Matrix:", null_space_basis_B)

print("Basis for the null space of Magic Matrix:", null_space_basis_C)

Hilbert Matrix = 
 [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]

Pascal Matrix = 
 [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [1. 3. 3. 1. 0.]
 [1. 4. 6. 4. 1.]]

Magic matrix = 
 [[ 9  3 22 16 15]
 [ 2 21 20 14  8]
 [25 19 13  7  1]
 [18 12  6  5 24]
 [11 10  4 23 17]]

Basis for the null space of Hilbert Matrix: []
Basis for the null space of Pascal Matrix: []
Basis for the null space of Magic Matrix: []


#Exercise 9

In [ ]:
def is_orthogonal_set(vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if vectors[i].shape != vectors[j].shape:
                return False
            if np.dot(vectors[i], vectors[j]) != 0:
                return False
    return True

A = np.array([
    [3, 1, 1],
    [-1, 2, 1],
    [-1/2, 2, 7/2]
]).T

if is_orthogonal_set(A):
    print("The vectors are orthogona")
else:
    print("The vectors are not orthogonal")

The vectors are not orthogonal


#Exercise 10

In [ ]:
def orthogonal_projection(y, u):
    projection = np.dot(y, u) / np.dot(u, u) * u
    return projection

y = np.array([7, 6])
u = np.array([4, 2])

proj_u_y = orthogonal_projection(y.T, u.T)
print("The orthogonal projection of y on u is:", proj_u_y)

The orthogonal projection of y on u is: [8. 4.]


#Exercise 11

In [ ]:
def has_orthonormal_columns(A):
    U = A / np.linalg.norm(A, axis=0) 
    UTU = np.dot(U.T, U) 
    return np.allclose(UTU, np.eye(UTU.shape[0]))

A = np.array([
    [1, 0],
    [0, 1],
    [1, 1]
])

B = np.array([
    [1, 0, 0], 
    [0, 1, 0],
    [0, 0, 1]
])

print("Has orthonormal column:", has_orthonormal_columns(A))
print("Has orthonormal column:",has_orthonormal_columns(B)) 


Has orthonormal column: False
Has orthonormal column: True


#Exercise 12

In [ ]:
def gram_schmidt(A):
    Q = np.zeros_like(A)                                  #initialize Q matrix
    for i in range(A.shape[1]):
        v = A[:, i]                                       #select a column vector from A
        for j in range(i):
            q = Q[:, j]                                   #select a column vector from Q
            v -= np.dot(v, q) * q                         #subtract the projection of v onto q from v
        Q[:, i] = v / np.linalg.norm(v)                   #normalize v and add it to Q
    return Q

A = np.array([
    [-10, 13, 7, -11], 
    [2, 1, -5, 3], 
    [-6, 3, 13, -3], 
    [16, -16, -2, 5], 
    [2, 1, -5, -7]
])

print("Orthogonal basis for column space of A = \n", gram_schmidt(A))

Orthogonal basis for column space of A = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
