# Exercise 1:
Write command to find 1-norm of the following matrices:

In [4]:
import numpy as np

Note: Do not use the built-in function (i.e. norm function) to find norm.

In [2]:
A1 = np.array([[1, -7], [-2, -3]])
A2 = np.array([[3, 6], [1, 0]])
A3 = np.array([[5, -4, 2], [-1, 2, 3], [-2, 1, 0]])
A4 = np.array([[2, 3], [1, -1]])
A5 = np.array([[5, -4, 2], [-1, 2, 3], [-2, 1, 0]])


norm_1_A1 = np.linalg.norm(A1, 1)
norm_1_A2 = np.linalg.norm(A2, 1)
norm_1_A3 = np.linalg.norm(A3, 1)
norm_1_A4 = np.linalg.norm(A4, 1)
norm_1_A5 = np.linalg.norm(A5, 1)

print("1-norm of A1 =", norm_1_A1)
print("1-norm of A2 =", norm_1_A2)
print("1-norm of A3 =", norm_1_A3)
print("1-norm of A4 =", norm_1_A4)
print("1-norm of A5 =", norm_1_A5)

1-norm of A1 = 10.0
1-norm of A2 = 6.0
1-norm of A3 = 8.0
1-norm of A4 = 4.0
1-norm of A5 = 8.0


# Exercise 2:
Write command to find infinity-norm of the following matrices:

Note: Do not use the built-in function (i.e. norm function) to find norm.

In [ ]:
B1 = np.array([[1, -7], [-2, -3]])
B2 = np.array([[3, 6], [1, 0]])
B3 = np.array([[5, -4, 2], [-1, 2, 3], [-2, 1, 0]])
B4 = np.array([[3, 6, -1], [3, 1, 0], [2, 4, -7]])
B5 = np.array([[-3, 0, 0], [0, 4, 0], [0, 0, 2]])

norm_infinity_B1 = np.linalg.norm(B1, np.inf)
norm_infinity_B2 = np.linalg.norm(B2, np.inf)
norm_infinity_B3 = np.linalg.norm(B3, np.inf)
norm_infinity_B4 = np.linalg.norm(B4, np.inf)
norm_infinity_B5 = np.linalg.norm(B5, np.inf)

print("Infinity norm of B1 =", norm_infinity_B1)
print("Infinity norm of B2 =", norm_infinity_B2)
print("Infinity norm of B3 =", norm_infinity_B3)
print("Infinity norm of B4 =", norm_infinity_B4)
print("Infinity norm of B5 =", norm_infinity_B5)

Infinity norm of B1 = 8.0
Infinity norm of B2 = 9.0
Infinity norm of B3 = 11.0
Infinity norm of B4 = 13.0
Infinity norm of B5 = 4.0


# Exercise 3:
Write command to find calculate the Frobenius-norm

Note: Do not use the built-in function (i.e. norm function) to find norm.

In [ ]:
C1 = np.array([[5, -4, 2], [-1, 2, 3], [-2, 1, 0]])
C2 = np.array([[1, 7, 3], [4, -2, -2], [-2, -1, 1]])
C3 = np.array([[2, 3], [1, -1]])

# Frobenius  căn bậc 2 các phần tử trong ma trận rồi căn bậc 2 chúng

norm_frobenius_C1 = np.linalg.norm(C1, "fro")
norm_frobenius_C2 = np.linalg.norm(C2, "fro")
norm_frobenius_C3 = np.linalg.norm(C3, "fro")

print("Frobenius norm of C1 =", norm_frobenius_C1)
print("Frobenius norm of C2 =", norm_frobenius_C2)
print("Frobenius norm of C3 =", norm_frobenius_C3)

Frobenius norm of C1 = 8.0
Frobenius norm of C2 = 9.433981132056603
Frobenius norm of C3 = 3.872983346207417


# Exercise 4:
Let u and v be vectors in R^2. For the following u and v determine the angle between the vectors.

In [ ]:
u_a = np.array([1, 1])
v_a = np.array([0, 1])

u_b = np.array([1, 0])
v_b = np.array([0, 1])

u_c = np.array([-2, 3])
v_c = np.array([1 / 2, -1 / 2])

a_angle = u_a.dot(v_a) / (np.linalg.norm(u_a) * np.linalg.norm(v_a))
b_angle = u_a.dot(v_b) / (np.linalg.norm(u_b) * np.linalg.norm(v_b))
c_angle = u_a.dot(v_c) / (np.linalg.norm(u_c) * np.linalg.norm(v_c))


print(
    "A. Angle between u and v is:", round(np.degrees(np.arccos(a_angle)), 5), "degree"
)
print(
    "B. Angle between u and v is:", round(np.degrees(np.arccos(b_angle)), 5), "degree"
)
print(
    "C. Angle between u and v is:", round(np.degrees(np.arccos(c_angle)), 5), "degree"
)

A. Angle between u and v is: 45.0 degree
B. Angle between u and v is: 0.0 degree
C. Angle between u and v is: 90.0 degree


# Exercise 5:
Determine the unit vector u for each of the following vectors.

In [ ]:
u1 = np.array([2, 3])
u2 = np.array([1, 2, 3])
u3 = np.array([1 / 2, -1 / 2, 1 / 4])
u4 = np.array([2 ** (1 / 2), 2, -(2 ** (1 / 2)), 2 ** (1 / 2)])

unit_u1 = u1 / np.linalg.norm(u1)
unit_u2 = u2 / np.linalg.norm(u2)
unit_u3 = u3 / np.linalg.norm(u3)
unit_u4 = u4 / np.linalg.norm(u4)

print("Unit vecto of u is", unit_u1, "with 2-norm =", np.linalg.norm(unit_u1))
print("Unit vecto of u is", unit_u2, "with 2-norm =", np.linalg.norm(unit_u2))
print("Unit vecto of u is", unit_u3, "with 2-norm =", np.linalg.norm(unit_u3))
print("Unit vecto of u is", unit_u4, "with 2-norm =", np.linalg.norm(unit_u4))

Unit vecto of u is [0.5547002  0.83205029] with 2-norm = 1.0
Unit vecto of u is [0.26726124 0.53452248 0.80178373] with 2-norm = 1.0
Unit vecto of u is [ 0.66666667 -0.66666667  0.33333333] with 2-norm = 1.0
Unit vecto of u is [ 0.4472136   0.63245553 -0.4472136   0.4472136 ] with 2-norm = 0.9999999999999999


# Exercise 6:
Let v1 = (1, 2, 3).T, s2 = (7, 4, 3).T, and s3 = (2, 1, 9).T be the position of three satellites. Find the Euclidean distances between satellites.

In [ ]:
v1 = np.array([1, 2, 3])
s2 = np.array([7, 4, 3])
s3 = np.array([2, 1, 9])

# Tích độ dài 2 điểm trừ nhau = khoảng cách giữa 2 điểm
distant_v1_s2 = np.linalg.norm(v1 - s2)
distant_v1_s3 = np.linalg.norm(v1 - s3)
distant_s2_s3 = np.linalg.norm(s2 - s3)

print("Distance between v1 and s2 =", distant_v1_s2)
print("Distance between v1 and s3 =", distant_v1_s3)
print("Distance between s2 and s3 =", distant_s2_s3)

# Exercise 7
Write a function to decode the encoded following message

Hint: In order to decode the message D, you need to know the inverse matrix A−1 and then you calculate A^(−1)E to get the matrix D. Remember that the matrix D contains the message. Finally, using the above lookup table to obtain the message which can read.

In [ ]:
# np.linalg.inv(): Tìm ma trận nghịch đảo

E = np.array(
    [
        [80, 98, 99, 85, 106, 94],
        [71, 92, 76, 95, 100, 92],
        [124, 163, 140, 160, 176, 161],
    ]
)

A = np.array([[1, 2, 3], [2, 1, 2], [3, 2, 4]])

D = np.matmul(np.linalg.inv(A), E)

print(D)

msg = ""

for col in range(D.shape[1]):
    for row in range(D.shape[0]):
        if int(round(D[row, col])) == 30:
            msg += " "
        else:
            msg += chr(65 + int(round(D[row, col], 0)) - 4)


print("Message of D:", msg)

[[18. 21. 12. 30. 24. 23.]
 [19.  4. 18.  5.  8.  4.]
 [ 8. 23. 17. 15. 22. 21.]]
Message of D: OPERATION BLUESTAR


# Exercise 8

In [3]:
#list char (look up table)
lchar = list(map(chr, range(97 - 32, 123 - 32)))
lchar.append(" ")

#initiate an array A
A = np.array([
    [3, 4, 5],
    [1, 3, 1],
    [1, 1, 2]
])

#initiate 2 encode result
res1 = []
res2 = []

msg1 = list("ATTACK")
msg2 = list(" LINEAR ALGEBRA LABORATORY ")

#encode msg1 
for i in msg1:
  for j in range(0, len(lchar), 1):
    if i == lchar[j]:
      res1.append(j + 4)

encode1 = np.array(res1)
encode1 = encode1.reshape(3, 2)
result1 = np.matmul(A, encode1)
print("ATTACK = ")
print(result1, "\n")

#encode msg2
for i in msg2:
  for j in range(0, len(lchar), 1):
    if i == lchar[j]:
      res2.append(j + 4)

encode2 = np.array(res2)
encode2 = encode2.reshape(3, 9)
result2 = np.matmul(A, encode2)
print("LINEAR ALGEBRA LABORATORY = ")
print(result2)

ATTACK = 
[[134 155]
 [ 79  49]
 [ 39  55]] 

LINEAR ALGEBRA LABORATORY = 
[[175 175 173  91 223 118 288 290 178]
 [ 80  63  57  36  94  34 132 103  46]
 [ 55  61  62  30  75  44  93 101  68]]


# Exercise 9

In [6]:
def cosine_similarity(matrix):
  prod = np.matmul(matrix, matrix.T)

  norm = np.sqrt(np.sum(matrix**2, axis = 1))

  outer_norm = np.outer(norm, norm)

  cosine_similarity_matrix = prod/outer_norm
  
  return cosine_similarity_matrix

A = np.array([
    [0, 4, 0, 0, 0, 2, 1, 3],
    [3, 1, 4, 3, 1, 2, 0, 1],
    [3, 0, 0, 0, 3, 0, 3, 0],
    [0, 1, 0, 3, 0, 0, 2, 0],
    [2, 2, 2, 3, 1, 4, 0, 2]
])

print("cosine similarity matrix = \n", cosine_similarity(A))

cosine similarity matrix = 
 [[1.         0.31364627 0.10540926 0.29277002 0.61977979]
 [0.31364627 1.         0.36066785 0.41739194 0.86753285]
 [0.10540926 0.36066785 1.         0.3086067  0.26726124]
 [0.29277002 0.41739194 0.3086067  1.         0.45363235]
 [0.61977979 0.86753285 0.26726124 0.45363235 1.        ]]


# Exercise 10

In [5]:
def retrieve_nearest_doc(q, doc_vector):
  similarities = np.matmul(doc_vector, q) / (np.linalg.norm(doc_vector, axis = 1) * np.linalg.norm(q))

  nearest_doc_index = np.argmax(similarities)

  return nearest_doc_index

vector = np.array([
    [1.0, 0.5, 0.3, 0, 0, 0],
    [0.5, 1.0, 0, 0, 0, 0],
    [0, 1.0, 0.8, 0.7, 0, 0],
    [0, 0.9, 1.0, 0.5, 0, 0],
    [0, 0, 0, 1.0, 0, 1.0],
    [0, 0, 0, 0, 0.7, 0],
    [0.5, 0, 0.7, 0, 0, 0.9],
    [0, 0.6, 0, 1.0, 0.3, 0.2]
])

q = np.array([0, 0, 0.7, 0.5, 0, 0.3])

print("The nearest document is D:", retrieve_nearest_doc(q, vector) + 1)

The nearest document is D: 4
