**Input**
Create a 10×10 matrix A with random integers [1, 99].

#Exercise 11:
 Chemical equations describe the quantities of substances consumed and produced by chemical
reactions. For instance

(x1)C3H8 + (x2)O2 −→ (x3)CO2 + (x4)H2O

To balance this equation, a chemist must find whole numbers x1, ..., x4 such that the total numbers
of carbon (C), hydrogen (H), and oxygen (O) atoms on the left match the corresponding numbers of
atoms on the right.
Hint: Three types of atoms (C, H, O) construct a vector in R3
.

In [ ]:
import numpy as np

# Hệ số ma trận
A = np.array([[3, 0, -3, 0],
              [8, 0, -4, -2],
              [0, 10, -2, -4]])

# Véc tơ bên phải
b = np.array([0, 0, 0])

# Giải bằng hàm linalg.solve
x = np.linalg.solve(A, b)

# In kết quả
print(x)


In [ ]:
import numpy as np

A = np.random.randint(1, 100, size=(10, 10))


**Excercise 12:** Save odd columns of the matrix A into a new matrix.

In [ ]:
B = A[:, ::2]
print(B)


[[82 80 83 60 36]
 [33 51 95 71 94]
 [81 91 57 44 72]
 [44 90 42 73 76]
 [84 10 69 89 27]
 [53 47 99 85 37]
 [22 29 81 54 39]
 [85 74 64 92 77]
 [74 50 39 30 77]
 [58 72 45 23 93]]


**Excercise 13:** Save even rows of the matrix A into a new matrix.

In [ ]:
B = A[1::2]
print(B)


[[33 50 51 25 95 56 71 21 94 93]
 [44 19 90 35 42 86 73 32 76 31]
 [53 32 47 46 99 35 85  4 37 64]
 [85 92 74 92 64 75 92 14 77 79]
 [58 28 72 14 45 92 23 29 93 88]]


**Excercise 14:** Save even integer numbers in the matrix A into a vector.

In [ ]:
B = []

for row in A:
    for element in row:
        if element % 2 == 0:
            B.append(element)

print(B)


[22, 86, 54, 56, 10, 84, 22, 4, 58, 88, 8, 70, 36, 42, 72, 58, 94, 16, 82, 20, 62, 64, 46, 4, 2, 70, 50, 34, 44, 86, 78, 42, 86, 84, 26, 82, 34, 66, 36, 60, 2, 8]


**Excercise 15:** Reverse elements in the even rows of the matrix A, and save the results into a new matrix.

In [ ]:
# cau15
B = A.copy()

# Loop and flip over the even rows in B
for i in range(1, len(B), 2):
    B[i] = np.flipud(B[i])

print(B)


[[82 25 80 63 83 39 60 84 36 19]
 [93 94 21 71 56 95 33 50 51 25]
 [81 44 91 26 57 45 44 18 72 50]
 [31 76 32 73 86 42 44 19 90 35]
 [84 97 10 60 69 34 89  2 27 19]
 [64 37  4 85 35 99 53 32 47 46]
 [22 11 29 63 81  8 54 40 39 14]
 [79 77 14 92 75 64 85 92 74 92]
 [74 74 50 50 39 38 30 78 77 39]
 [88 93 29 23 92 45 58 28 72 14]]


Another Way for **Excercise 5**

In [ ]:
# Create a new empty matrix with the same shape as A
B = [[0 for _ in range(len(A[0]))] for _ in range(len(A))]

# Loop over the rows in A
for i, row in enumerate(A):
    # Reverse the elements in even rows
    if i % 2 == 0:
        row = np.flipud(row)
    # Copy the row into the new matrix
    B[i] = row

# Print the original and new matrices for comparison
print("New matrix B:")
for row in B:
    print(row)


New matrix B:
[19 36 84 60 39 83 63 80 25 82]
[25 51 50 33 95 56 71 21 94 93]
[50 72 18 44 45 57 26 91 44 81]
[35 90 19 44 42 86 73 32 76 31]
[19 27  2 89 34 69 60 10 97 84]
[46 47 32 53 99 35 85  4 37 64]
[14 39 40 54  8 81 63 29 11 22]
[92 74 92 85 64 75 92 14 77 79]
[39 77 78 30 38 39 50 50 74 74]
[14 72 28 58 45 92 23 29 93 88]


**Excercise 16:** Replace odd integer numbers in the matrix A by the maximum odd integer number of A.

In [ ]:
B = A.copy()

maxNum = B[0][0]

for row in B:
    for element in row:
        if (element % 2 != 0) and (element > maxNum):
            maxNum = element

for i in range(len(B)):
    for j in range(len(B[i])):
        if B[i][j] % 2 != 0:
            B[i][j] = maxNum

print(B)


[[95 22 86 54 95 95 95 56 95 10]
 [95 95 95 95 84 95 95 95 95 22]
 [95  4 95 58 88 95 95  8 70 36]
 [95 42 95 95 95 95 95 95 95 95]
 [72 95 58 95 94 95 16 82 95 20]
 [95 95 62 95 64 95 95 46  4 95]
 [95  2 95 70 95 95 95 95 95 95]
 [95 95 50 95 34 95 44 95 86 95]
 [95 78 42 86 95 95 84 26 82 34]
 [66 95 36 60 95 95  2 95  8 95]]


**Excercise 17:** Swap the first column and the last column of the matrix A, and save the results into a new matrix.

Note: it is different with matrix flipping.

In [ ]:
B = A.copy()

for i in range(len(B)):
    B[i] = np.flipud(B[i])

print(B)


[[10 17 56 75 35 69 54 86 22 19]
 [22  3  5 49 73 84 39 17 75 73]
 [36 70  8 21 47 88 58 83  4 83]
 [65 15 17 73 89 61 41 21 42 21]
 [20  7 82 16  1 94 91 58 65 72]
 [53  4 46 55 23 64 63 62  5 25]
 [ 9 45 93 59  7 31 70 63  2 11]
 [35 86 21 44 85 34 95 50 95 13]
 [34 82 26 84 83 43 86 42 78 29]
 [21  8 75  2  5 81 60 36  3 66]]


**Excercise 18:** Calculate sum of all Boundary elements of the matrix A, and save the result into a variable.

Hint:
- Boundary elements are those elements that are not surrounded by elements in all four directions, i.e. elements in the first row, first column, last row, and last column.
- To avoid duplicated calculation, each element must be used only one time in the sum calculation.

Đây là một đoạn chương trình Python để tính tổng các phần tử ở hàng đầu tiên, hàng cuối cùng, cột đầu tiên và cột cuối cùng của ma trận đa chiều A.

**for i in range(len(B)):** Duyệt qua từng phần tử của hàng đầu tiên và hàng cuối cùng của ma trận B, với i là chỉ số của các phần tử đó.

**sum += B[0][i]:** Cộng giá trị của phần tử thứ i trong hàng đầu tiên của ma trận B vào biến sum.

**sum += B[len(B)-1][i]:** Cộng giá trị của phần tử thứ i trong hàng cuối cùng của ma trận B vào biến sum.

**for i in range(1, len(B) - 1):** Duyệt qua từng phần tử của cột đầu tiên và cột cuối cùng của ma trận B, với i là chỉ số của các phần tử đó. Lưu ý rằng chỉ duyệt từ phần tử thứ 2 đến phần tử thứ len(B) - 2 để tránh tính lại các phần tử đã được tính ở hàng đầu tiên và hàng cuối cùng.

**sum += B[i][0]:** Cộng giá trị của phần tử đầu tiên trong cột thứ i của ma trận B vào biến sum.

**sum += B[i][len(B[0])-1]:** Cộng giá trị của phần tử cuối cùng trong cột thứ i của ma trận B vào biến sum.






In [ ]:
B = A.copy()

sum = 0

# duyệt qua hàng đầu tiên và hàng cuối cùng
for i in range(len(B)):
    sum += B[0][i]
    sum += B[len(B)-1][i]

# duyệt qua cột đầu tiên và cột cuối cùng
for i in range(1, len(B) - 1):
    sum += B[i][0]
    sum += B[i][len(B[0])-1]

print(sum)


1401


Calculate sum of all major and minor Diagonal elements of the matrix A, and save the result into a variable.

Hint:
- Major diagonal elements are the ones that occur from TOP LEFT of matrix down to BOTTOM RIGHT corner.
Minor diagonal elements are the ones that occur from TOP RIGHT of matrix down to BOTTOM LEFT corner.
- To avoid duplicated calculation, each element must be used only one time in the sum calculation.

In [ ]:
sum_major = 0
sum_minor = 0

# Duyệt qua từng phần tử của ma trận
for i in range(len(A)):
    for j in range(len(A[0])):
        # Kiểm tra xem phần tử đó có nằm trên đường chéo chính hay không
        if i == j:
            sum_major += A[i][j]
        # Kiểm tra xem phần tử đó có nằm trên đường chéo phụ hay không
        if i + j == len(A) - 1:
            sum_minor += A[i][j]

# Trừ đi các phần tử trùng nhau giữa đường chéo chính và đường chéo phụ
if len(A) % 2 == 1:
    common_element = A[len(A) // 2][len(A) // 2]
    sum_minor -= common_element
    sum_major -= common_element

# In ra tổng các phần tử trên đường chéo chính và đường chéo phụ
print("Sum of major diagonal elements:", sum_major)
print("Sum of minor diagonal elements:", sum_minor)
print("Total sum:", sum_major + sum_minor)


Sum of major diagonal elements: 518
Sum of minor diagonal elements: 423
Total sum: 941


In [ ]:
B = A.copy()

sum = 0

for i in range(len(A)):
    sum += i

print(sum)


45


Write python code:

Given a table containing the values of the coordinate points of the graph (x) = c1 + c2x + c3 * x ** 2  + c4 * x ** 3

x: 1, 2, 3, 4

fx: 1000, 2000, 3000, 4000

Find the coefficients c1, c2, c3, c4

In [1]:
# Define the values of x and fx
x = np.array([1, 2, 3, 4])
fx = np.array([1000, 2000, 3000, 4000])

# Define the matrix A and the vector b for the linear system Ax = b
A = np.array([
    [1, x[0], x[0]**2, x[0]**3],
    [1, x[1], x[1]**2, x[1]**3],
    [1, x[2], x[2]**2, x[2]**3],
    [1, x[3], x[3]**2, x[3]**3]
])
b = fx.reshape((-1, 1))

# Solve the linear system using the method of least squares
coeffs = np.linalg.solve(np.matmul(A.T, A), np.matmul(A.T, b))

# Print the coefficients c1, c2, c3, c4
c1, c2, c3, c4 = coeffs.flatten()
print(f"c1 = {c1}, c2 = {c2}, c3 = {c3}, c4 = {c4}")


c1 = 2.869637683033943e-10, c2 = 999.9999999995498, c3 = 1.9933092213839895e-10, c4 = -2.627429138452921e-11
